name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: dotnet publish --no-build -c Release -o packages/api
    - name: deploy on azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: hilfswerk-api
        publish-profile: ${{ secrets.hilfswerk_api_publish_profile }}
        package: ./packages/api
    - name: Build
      working-directory: src/frontend
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod --base-href="/hilfswerk/"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: src/frontend/dist/frontend
