name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: dotnet publish --no-build -c Release -o packages/api
    - name: deploy on azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: hilfswerk-api
        publish-profile: ${{ secrets.hilfswerk_api_publish_profile }}
        package: ./packages/api
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Build
      working-directory: src/frontend
      run: |
        npm ci
        npm run build -- --prod --base-href="/hilfswerk/"
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        # Git branch where assets will be deployed
        target_branch: gh-pages
        # Build directory to deploy
        build_dir: src/frontend/dist/fronted
